# Generated by Django 4.1 on 2022-10-15 08:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=255)),
                ('Lastname', models.CharField(max_length=255)),
                ('Username', models.CharField(max_length=244, unique=True)),
                ('Password', models.CharField(max_length=255)),
                ('mobileNumber', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 14 digits allowed.", regex='^\\+?1?\\d{9,14}$')])),
            ],
            options={
                'db_table': 'Players',
            },
        ),
        migrations.CreateModel(
            name='GameBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_String', models.CharField(default=True, max_length=6, null=True)),
                ('Palindrome', models.CharField(max_length=6)),
                ('PalyerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Player', to='Palindrome.player')),
            ],
            options={
                'db_table': 'GameBoard',
            },
        ),
    ]
